import dayjs from 'dayjs/esm';
import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

export interface IFieldTestInfiniteScrollEntity {
  id: string;
  stringHugo?: string | null;
  stringRequiredHugo?: string | null;
  stringMinlengthHugo?: string | null;
  stringMaxlengthHugo?: string | null;
  stringPatternHugo?: string | null;
  integerHugo?: number | null;
  integerRequiredHugo?: number | null;
  integerMinHugo?: number | null;
  integerMaxHugo?: number | null;
  longHugo?: number | null;
  longRequiredHugo?: number | null;
  longMinHugo?: number | null;
  longMaxHugo?: number | null;
  floatHugo?: number | null;
  floatRequiredHugo?: number | null;
  floatMinHugo?: number | null;
  floatMaxHugo?: number | null;
  doubleRequiredHugo?: number | null;
  doubleMinHugo?: number | null;
  doubleMaxHugo?: number | null;
  bigDecimalRequiredHugo?: number | null;
  bigDecimalMinHugo?: number | null;
  bigDecimalMaxHugo?: number | null;
  localDateHugo?: dayjs.Dayjs | null;
  localDateRequiredHugo?: dayjs.Dayjs | null;
  instantHugo?: dayjs.Dayjs | null;
  instanteRequiredHugo?: dayjs.Dayjs | null;
  zonedDateTimeHugo?: dayjs.Dayjs | null;
  zonedDateTimeRequiredHugo?: dayjs.Dayjs | null;
  durationHugo?: string | null;
  durationRequiredHugo?: string | null;
  booleanHugo?: boolean | null;
  booleanRequiredHugo?: boolean | null;
  enumHugo?: EnumFieldClass | null;
  enumRequiredHugo?: EnumRequiredFieldClass | null;
  uuidHugo?: string | null;
  uuidRequiredHugo?: string | null;
  byteImageHugo?: string | null;
  byteImageHugoContentType?: string | null;
  byteImageRequiredHugo?: string | null;
  byteImageRequiredHugoContentType?: string | null;
  byteImageMinbytesHugo?: string | null;
  byteImageMinbytesHugoContentType?: string | null;
  byteImageMaxbytesHugo?: string | null;
  byteImageMaxbytesHugoContentType?: string | null;
  byteAnyHugo?: string | null;
  byteAnyHugoContentType?: string | null;
  byteAnyRequiredHugo?: string | null;
  byteAnyRequiredHugoContentType?: string | null;
  byteAnyMinbytesHugo?: string | null;
  byteAnyMinbytesHugoContentType?: string | null;
  byteAnyMaxbytesHugo?: string | null;
  byteAnyMaxbytesHugoContentType?: string | null;
  byteTextHugo?: string | null;
  byteTextRequiredHugo?: string | null;
}

export type NewFieldTestInfiniteScrollEntity = Omit<IFieldTestInfiniteScrollEntity, 'id'> & { id: null };
