import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import { IFieldTestInfiniteScrollEntity, NewFieldTestInfiniteScrollEntity } from './field-test-infinite-scroll-entity.model';

export const sampleWithRequiredData: IFieldTestInfiniteScrollEntity = {
  id: '1c76c8d6-a9ed-47de-857b-e0769e2df355',
  stringRequiredHugo: 'Southwest',
  integerRequiredHugo: 23908,
  longRequiredHugo: 84778,
  floatRequiredHugo: 89179,
  doubleRequiredHugo: 10513,
  bigDecimalRequiredHugo: 15719,
  localDateRequiredHugo: dayjs('2016-02-08'),
  instanteRequiredHugo: dayjs('2016-02-08T16:19'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-08T14:22'),
  durationRequiredHugo: '76720',
  booleanRequiredHugo: false,
  enumRequiredHugo: EnumRequiredFieldClass['ENUM_VALUE_2'],
  uuidRequiredHugo: '92e4526c-7579-4776-adad-e087e868ef8c',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestInfiniteScrollEntity = {
  id: '8b34ac83-4860-414f-91f5-dca8c4698f83',
  stringHugo: 'Pizza burble',
  stringRequiredHugo: 'system',
  stringMaxlengthHugo: 'Electric',
  integerRequiredHugo: 38997,
  longHugo: 7824,
  longRequiredHugo: 86446,
  floatHugo: 86988,
  floatRequiredHugo: 15018,
  floatMaxHugo: 94,
  doubleRequiredHugo: 44718,
  doubleMaxHugo: 92,
  bigDecimalRequiredHugo: 84939,
  localDateRequiredHugo: dayjs('2016-02-08'),
  instanteRequiredHugo: dayjs('2016-02-08T16:00'),
  zonedDateTimeHugo: dayjs('2016-02-07T20:36'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-08T12:07'),
  durationHugo: '6449',
  durationRequiredHugo: '12086',
  booleanRequiredHugo: false,
  enumHugo: EnumFieldClass['ENUM_VALUE_3'],
  enumRequiredHugo: EnumRequiredFieldClass['ENUM_VALUE_3'],
  uuidHugo: '6fc293c2-63a7-4913-a6a8-0d50e7766b43',
  uuidRequiredHugo: '6edc13da-2b3d-45a9-baeb-ef7f878b7626',
  byteImageHugo: '../fake-data/blob/hipster.png',
  byteImageHugoContentType: 'unknown',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteAnyMinbytesHugo: '../fake-data/blob/hipster.png',
  byteAnyMinbytesHugoContentType: 'unknown',
  byteTextHugo: '../fake-data/blob/hipster.txt',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestInfiniteScrollEntity = {
  id: 'ec70acf9-3053-484b-96c3-242a5e5bd54d',
  stringHugo: 'Van',
  stringRequiredHugo: 'Associate',
  stringMinlengthHugo: 'North deserunt',
  stringMaxlengthHugo: 'Southeast redundant',
  stringPatternHugo: undefined,
  integerHugo: 89272,
  integerRequiredHugo: 65242,
  integerMinHugo: 41782,
  integerMaxHugo: 83,
  longHugo: 69313,
  longRequiredHugo: 45033,
  longMinHugo: 74755,
  longMaxHugo: 21,
  floatHugo: 83156,
  floatRequiredHugo: 31181,
  floatMinHugo: 25380,
  floatMaxHugo: 64,
  doubleRequiredHugo: 82623,
  doubleMinHugo: 84134,
  doubleMaxHugo: 83,
  bigDecimalRequiredHugo: 98324,
  bigDecimalMinHugo: 30878,
  bigDecimalMaxHugo: 93,
  localDateHugo: dayjs('2016-02-08'),
  localDateRequiredHugo: dayjs('2016-02-08'),
  instantHugo: dayjs('2016-02-07T20:39'),
  instanteRequiredHugo: dayjs('2016-02-08T11:12'),
  zonedDateTimeHugo: dayjs('2016-02-08T15:02'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-07T21:06'),
  durationHugo: '75715',
  durationRequiredHugo: '23238',
  booleanHugo: false,
  booleanRequiredHugo: false,
  enumHugo: EnumFieldClass['ENUM_VALUE_2'],
  enumRequiredHugo: EnumRequiredFieldClass['ENUM_VALUE_3'],
  uuidHugo: '048931c0-ac89-40da-94cf-3b22823208fb',
  uuidRequiredHugo: '28f851f6-57cf-463a-8ebd-1e5122e30652',
  byteImageHugo: '../fake-data/blob/hipster.png',
  byteImageHugoContentType: 'unknown',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteImageMinbytesHugo: '../fake-data/blob/hipster.png',
  byteImageMinbytesHugoContentType: 'unknown',
  byteImageMaxbytesHugo: '../fake-data/blob/hipster.png',
  byteImageMaxbytesHugoContentType: 'unknown',
  byteAnyHugo: '../fake-data/blob/hipster.png',
  byteAnyHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteAnyMinbytesHugo: '../fake-data/blob/hipster.png',
  byteAnyMinbytesHugoContentType: 'unknown',
  byteAnyMaxbytesHugo: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesHugoContentType: 'unknown',
  byteTextHugo: '../fake-data/blob/hipster.txt',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestInfiniteScrollEntity = {
  stringRequiredHugo: 'Synchronised',
  integerRequiredHugo: 37104,
  longRequiredHugo: 26884,
  floatRequiredHugo: 19001,
  doubleRequiredHugo: 86996,
  bigDecimalRequiredHugo: 37391,
  localDateRequiredHugo: dayjs('2016-02-08'),
  instanteRequiredHugo: dayjs('2016-02-08T12:47'),
  zonedDateTimeRequiredHugo: dayjs('2016-02-08T18:26'),
  durationRequiredHugo: '75083',
  booleanRequiredHugo: true,
  enumRequiredHugo: EnumRequiredFieldClass['ENUM_VALUE_1'],
  uuidRequiredHugo: 'de44f5bf-bf96-425d-afad-84b57e677305',
  byteImageRequiredHugo: '../fake-data/blob/hipster.png',
  byteImageRequiredHugoContentType: 'unknown',
  byteAnyRequiredHugo: '../fake-data/blob/hipster.png',
  byteAnyRequiredHugoContentType: 'unknown',
  byteTextRequiredHugo: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
