import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import { IFieldTestEntity, NewFieldTestEntity } from './field-test-entity.model';

export const sampleWithRequiredData: IFieldTestEntity = {
  id: '74b30188-d1b6-4ed4-b7a0-19231d16eba7',
  stringRequiredTom: 'Fitness second Rupee',
  numberPatternRequiredTom: '142',
  integerRequiredTom: 19517,
  longRequiredTom: 92889,
  floatRequiredTom: 76928,
  doubleRequiredTom: 44658,
  bigDecimalRequiredTom: 92543,
  localDateRequiredTom: dayjs('2016-02-08'),
  instantRequiredTom: dayjs('2016-02-08T06:07'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T13:04'),
  durationRequiredTom: '84899',
  booleanRequiredTom: false,
  enumRequiredTom: EnumRequiredFieldClass['ENUM_VALUE_3'],
  uuidRequiredTom: '9bc4f784-a238-4c9d-bf99-e27e50439359',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestEntity = {
  id: '3ca38845-e792-4001-b750-6faac4320db1',
  stringTom: 'Northeast Gasoline payment',
  stringRequiredTom: 'Burnsville',
  stringMinlengthTom: 'South wisely',
  numberPatternTom: '9',
  numberPatternRequiredTom: '4',
  integerRequiredTom: 53480,
  integerMinTom: 56601,
  integerMaxTom: 57,
  longTom: 7441,
  longRequiredTom: 2098,
  longMinTom: 84267,
  longMaxTom: 9,
  floatRequiredTom: 22532,
  floatMinTom: 80336,
  doubleRequiredTom: 64184,
  doubleMaxTom: 48,
  bigDecimalRequiredTom: 79358,
  bigDecimalMinTom: 78582,
  localDateRequiredTom: dayjs('2016-02-08'),
  instantTom: dayjs('2016-02-07T21:23'),
  instantRequiredTom: dayjs('2016-02-08T02:36'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T01:14'),
  durationRequiredTom: '27730',
  booleanRequiredTom: false,
  enumRequiredTom: EnumRequiredFieldClass['ENUM_VALUE_1'],
  uuidRequiredTom: '6e59d27f-7dbd-44a3-b7f9-ef0cdbf1bdd7',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteImageMinbytesTom: '../fake-data/blob/hipster.png',
  byteImageMinbytesTomContentType: 'unknown',
  byteImageMaxbytesTom: '../fake-data/blob/hipster.png',
  byteImageMaxbytesTomContentType: 'unknown',
  byteAnyTom: '../fake-data/blob/hipster.png',
  byteAnyTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteAnyMaxbytesTom: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesTomContentType: 'unknown',
  byteTextTom: '../fake-data/blob/hipster.txt',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestEntity = {
  id: 'd2731dd7-d89d-44d6-bd25-712ac6b2ec71',
  stringTom: 'integrated channels Automotive',
  stringRequiredTom: 'BMX',
  stringMinlengthTom: 'Ball',
  stringMaxlengthTom: 'Books male silver',
  stringPatternTom: '9et',
  numberPatternTom: '9',
  numberPatternRequiredTom: '720300',
  integerTom: 95057,
  integerRequiredTom: 26007,
  integerMinTom: 16156,
  integerMaxTom: 39,
  longTom: 62358,
  longRequiredTom: 70102,
  longMinTom: 95475,
  longMaxTom: 33,
  floatTom: 9420,
  floatRequiredTom: 22320,
  floatMinTom: 21092,
  floatMaxTom: 94,
  doubleRequiredTom: 24834,
  doubleMinTom: 78554,
  doubleMaxTom: 63,
  bigDecimalRequiredTom: 52612,
  bigDecimalMinTom: 57333,
  bigDecimalMaxTom: 51,
  localDateTom: dayjs('2016-02-08'),
  localDateRequiredTom: dayjs('2016-02-08'),
  instantTom: dayjs('2016-02-08T14:35'),
  instantRequiredTom: dayjs('2016-02-08T15:56'),
  zonedDateTimeTom: dayjs('2016-02-08T01:28'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T10:38'),
  durationTom: '45718',
  durationRequiredTom: '45079',
  booleanTom: false,
  booleanRequiredTom: true,
  enumTom: EnumFieldClass['ENUM_VALUE_1'],
  enumRequiredTom: EnumRequiredFieldClass['ENUM_VALUE_1'],
  uuidTom: '028fb677-e1ad-4540-b6ea-f51c76cc95a0',
  uuidRequiredTom: '9c59be97-7023-41db-ae14-504637fa8bd5',
  byteImageTom: '../fake-data/blob/hipster.png',
  byteImageTomContentType: 'unknown',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteImageMinbytesTom: '../fake-data/blob/hipster.png',
  byteImageMinbytesTomContentType: 'unknown',
  byteImageMaxbytesTom: '../fake-data/blob/hipster.png',
  byteImageMaxbytesTomContentType: 'unknown',
  byteAnyTom: '../fake-data/blob/hipster.png',
  byteAnyTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteAnyMinbytesTom: '../fake-data/blob/hipster.png',
  byteAnyMinbytesTomContentType: 'unknown',
  byteAnyMaxbytesTom: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesTomContentType: 'unknown',
  byteTextTom: '../fake-data/blob/hipster.txt',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestEntity = {
  stringRequiredTom: 'plum throughout New',
  numberPatternRequiredTom: '6551',
  integerRequiredTom: 67190,
  longRequiredTom: 70523,
  floatRequiredTom: 447,
  doubleRequiredTom: 35494,
  bigDecimalRequiredTom: 64583,
  localDateRequiredTom: dayjs('2016-02-07'),
  instantRequiredTom: dayjs('2016-02-08T03:01'),
  zonedDateTimeRequiredTom: dayjs('2016-02-08T11:38'),
  durationRequiredTom: '85636',
  booleanRequiredTom: true,
  enumRequiredTom: EnumRequiredFieldClass['ENUM_VALUE_1'],
  uuidRequiredTom: '340b5a96-8382-4ea1-b9df-bcd48a761be6',
  byteImageRequiredTom: '../fake-data/blob/hipster.png',
  byteImageRequiredTomContentType: 'unknown',
  byteAnyRequiredTom: '../fake-data/blob/hipster.png',
  byteAnyRequiredTomContentType: 'unknown',
  byteTextRequiredTom: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
