import dayjs from 'dayjs/esm';
import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

export interface IFieldTestServiceClassAndJpaFilteringEntity {
  id: string;
  stringBob?: string | null;
  stringRequiredBob?: string | null;
  stringMinlengthBob?: string | null;
  stringMaxlengthBob?: string | null;
  stringPatternBob?: string | null;
  integerBob?: number | null;
  integerRequiredBob?: number | null;
  integerMinBob?: number | null;
  integerMaxBob?: number | null;
  longBob?: number | null;
  longRequiredBob?: number | null;
  longMinBob?: number | null;
  longMaxBob?: number | null;
  floatBob?: number | null;
  floatRequiredBob?: number | null;
  floatMinBob?: number | null;
  floatMaxBob?: number | null;
  doubleRequiredBob?: number | null;
  doubleMinBob?: number | null;
  doubleMaxBob?: number | null;
  bigDecimalRequiredBob?: number | null;
  bigDecimalMinBob?: number | null;
  bigDecimalMaxBob?: number | null;
  localDateBob?: dayjs.Dayjs | null;
  localDateRequiredBob?: dayjs.Dayjs | null;
  instantBob?: dayjs.Dayjs | null;
  instanteRequiredBob?: dayjs.Dayjs | null;
  zonedDateTimeBob?: dayjs.Dayjs | null;
  zonedDateTimeRequiredBob?: dayjs.Dayjs | null;
  durationBob?: string | null;
  durationRequiredBob?: string | null;
  booleanBob?: boolean | null;
  booleanRequiredBob?: boolean | null;
  enumBob?: EnumFieldClass | null;
  enumRequiredBob?: EnumRequiredFieldClass | null;
  uuidBob?: string | null;
  uuidRequiredBob?: string | null;
  byteImageBob?: string | null;
  byteImageBobContentType?: string | null;
  byteImageRequiredBob?: string | null;
  byteImageRequiredBobContentType?: string | null;
  byteImageMinbytesBob?: string | null;
  byteImageMinbytesBobContentType?: string | null;
  byteImageMaxbytesBob?: string | null;
  byteImageMaxbytesBobContentType?: string | null;
  byteAnyBob?: string | null;
  byteAnyBobContentType?: string | null;
  byteAnyRequiredBob?: string | null;
  byteAnyRequiredBobContentType?: string | null;
  byteAnyMinbytesBob?: string | null;
  byteAnyMinbytesBobContentType?: string | null;
  byteAnyMaxbytesBob?: string | null;
  byteAnyMaxbytesBobContentType?: string | null;
  byteTextBob?: string | null;
  byteTextRequiredBob?: string | null;
}

export type NewFieldTestServiceClassAndJpaFilteringEntity = Omit<IFieldTestServiceClassAndJpaFilteringEntity, 'id'> & { id: null };
