import dayjs from 'dayjs/esm';
import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

export interface IFieldTestServiceImplEntity {
  id: string;
  stringMika?: string | null;
  stringRequiredMika?: string | null;
  stringMinlengthMika?: string | null;
  stringMaxlengthMika?: string | null;
  stringPatternMika?: string | null;
  integerMika?: number | null;
  integerRequiredMika?: number | null;
  integerMinMika?: number | null;
  integerMaxMika?: number | null;
  longMika?: number | null;
  longRequiredMika?: number | null;
  longMinMika?: number | null;
  longMaxMika?: number | null;
  floatMika?: number | null;
  floatRequiredMika?: number | null;
  floatMinMika?: number | null;
  floatMaxMika?: number | null;
  doubleRequiredMika?: number | null;
  doubleMinMika?: number | null;
  doubleMaxMika?: number | null;
  bigDecimalRequiredMika?: number | null;
  bigDecimalMinMika?: number | null;
  bigDecimalMaxMika?: number | null;
  localDateMika?: dayjs.Dayjs | null;
  localDateRequiredMika?: dayjs.Dayjs | null;
  instantMika?: dayjs.Dayjs | null;
  instanteRequiredMika?: dayjs.Dayjs | null;
  zonedDateTimeMika?: dayjs.Dayjs | null;
  zonedDateTimeRequiredMika?: dayjs.Dayjs | null;
  durationMika?: string | null;
  durationRequiredMika?: string | null;
  booleanMika?: boolean | null;
  booleanRequiredMika?: boolean | null;
  enumMika?: EnumFieldClass | null;
  enumRequiredMika?: EnumRequiredFieldClass | null;
  uuidMika?: string | null;
  uuidRequiredMika?: string | null;
  byteImageMika?: string | null;
  byteImageMikaContentType?: string | null;
  byteImageRequiredMika?: string | null;
  byteImageRequiredMikaContentType?: string | null;
  byteImageMinbytesMika?: string | null;
  byteImageMinbytesMikaContentType?: string | null;
  byteImageMaxbytesMika?: string | null;
  byteImageMaxbytesMikaContentType?: string | null;
  byteAnyMika?: string | null;
  byteAnyMikaContentType?: string | null;
  byteAnyRequiredMika?: string | null;
  byteAnyRequiredMikaContentType?: string | null;
  byteAnyMinbytesMika?: string | null;
  byteAnyMinbytesMikaContentType?: string | null;
  byteAnyMaxbytesMika?: string | null;
  byteAnyMaxbytesMikaContentType?: string | null;
  byteTextMika?: string | null;
  byteTextRequiredMika?: string | null;
}

export type NewFieldTestServiceImplEntity = Omit<IFieldTestServiceImplEntity, 'id'> & { id: null };
