import dayjs from 'dayjs/esm';

import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

import { IFieldTestServiceImplEntity, NewFieldTestServiceImplEntity } from './field-test-service-impl-entity.model';

export const sampleWithRequiredData: IFieldTestServiceImplEntity = {
  id: '46d270c8-ec9f-43a0-a830-0b0dfe8a104b',
  stringRequiredMika: 'vitae Convertible villainous',
  integerRequiredMika: 5924,
  longRequiredMika: 51344,
  floatRequiredMika: 53719,
  doubleRequiredMika: 33377,
  bigDecimalRequiredMika: 49836,
  localDateRequiredMika: dayjs('2016-02-07'),
  instanteRequiredMika: dayjs('2016-02-07T22:47'),
  zonedDateTimeRequiredMika: dayjs('2016-02-08T11:14'),
  durationRequiredMika: '91412',
  booleanRequiredMika: false,
  enumRequiredMika: EnumRequiredFieldClass['ENUM_VALUE_3'],
  uuidRequiredMika: '8d4924f0-90e3-429e-9acd-016e45ecada8',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
};

export const sampleWithPartialData: IFieldTestServiceImplEntity = {
  id: '273f651b-a0e9-4e2c-ac26-936a7a445ede',
  stringRequiredMika: 'Metrics Kwanza',
  stringMaxlengthMika: 'lavender Southeast i',
  integerRequiredMika: 386,
  integerMaxMika: 12,
  longRequiredMika: 75723,
  longMaxMika: 5,
  floatRequiredMika: 20227,
  doubleRequiredMika: 57731,
  doubleMinMika: 86578,
  doubleMaxMika: 63,
  bigDecimalRequiredMika: 46262,
  bigDecimalMinMika: 34641,
  bigDecimalMaxMika: 59,
  localDateMika: dayjs('2016-02-08'),
  localDateRequiredMika: dayjs('2016-02-07'),
  instantMika: dayjs('2016-02-08T18:23'),
  instanteRequiredMika: dayjs('2016-02-08T12:29'),
  zonedDateTimeRequiredMika: dayjs('2016-02-07T20:40'),
  durationRequiredMika: '91025',
  booleanMika: false,
  booleanRequiredMika: false,
  enumMika: EnumFieldClass['ENUM_VALUE_1'],
  enumRequiredMika: EnumRequiredFieldClass['ENUM_VALUE_2'],
  uuidRequiredMika: '69795ea7-567e-43b3-957c-7d38def62ad9',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteAnyMika: '../fake-data/blob/hipster.png',
  byteAnyMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteAnyMinbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMinbytesMikaContentType: 'unknown',
  byteAnyMaxbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesMikaContentType: 'unknown',
  byteTextMika: '../fake-data/blob/hipster.txt',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
};

export const sampleWithFullData: IFieldTestServiceImplEntity = {
  id: '374ce943-a4df-4980-8b86-d53e0e22ad27',
  stringMika: 'Gasoline Gasoline Reggae',
  stringRequiredMika: 'Grocery',
  stringMinlengthMika: 'Northeast Bronze DNS',
  stringMaxlengthMika: 'Tesla aha Steel',
  stringPatternMika: undefined,
  integerMika: 19936,
  integerRequiredMika: 44069,
  integerMinMika: 71402,
  integerMaxMika: 80,
  longMika: 58374,
  longRequiredMika: 36513,
  longMinMika: 18131,
  longMaxMika: 60,
  floatMika: 61341,
  floatRequiredMika: 38995,
  floatMinMika: 95167,
  floatMaxMika: 74,
  doubleRequiredMika: 75000,
  doubleMinMika: 42143,
  doubleMaxMika: 99,
  bigDecimalRequiredMika: 60441,
  bigDecimalMinMika: 11964,
  bigDecimalMaxMika: 7,
  localDateMika: dayjs('2016-02-08'),
  localDateRequiredMika: dayjs('2016-02-08'),
  instantMika: dayjs('2016-02-08T16:06'),
  instanteRequiredMika: dayjs('2016-02-08T14:16'),
  zonedDateTimeMika: dayjs('2016-02-08T03:05'),
  zonedDateTimeRequiredMika: dayjs('2016-02-08T01:06'),
  durationMika: '39067',
  durationRequiredMika: '66440',
  booleanMika: true,
  booleanRequiredMika: true,
  enumMika: EnumFieldClass['ENUM_VALUE_1'],
  enumRequiredMika: EnumRequiredFieldClass['ENUM_VALUE_2'],
  uuidMika: '71bad3e4-c7ca-42e6-b584-c9980b3da13f',
  uuidRequiredMika: '9f3fca98-d7d6-451e-bb14-a2a06995dba1',
  byteImageMika: '../fake-data/blob/hipster.png',
  byteImageMikaContentType: 'unknown',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteImageMinbytesMika: '../fake-data/blob/hipster.png',
  byteImageMinbytesMikaContentType: 'unknown',
  byteImageMaxbytesMika: '../fake-data/blob/hipster.png',
  byteImageMaxbytesMikaContentType: 'unknown',
  byteAnyMika: '../fake-data/blob/hipster.png',
  byteAnyMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteAnyMinbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMinbytesMikaContentType: 'unknown',
  byteAnyMaxbytesMika: '../fake-data/blob/hipster.png',
  byteAnyMaxbytesMikaContentType: 'unknown',
  byteTextMika: '../fake-data/blob/hipster.txt',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
};

export const sampleWithNewData: NewFieldTestServiceImplEntity = {
  stringRequiredMika: 'leverage Bedfordshire',
  integerRequiredMika: 94674,
  longRequiredMika: 5955,
  floatRequiredMika: 42061,
  doubleRequiredMika: 44752,
  bigDecimalRequiredMika: 77743,
  localDateRequiredMika: dayjs('2016-02-08'),
  instanteRequiredMika: dayjs('2016-02-08T01:39'),
  zonedDateTimeRequiredMika: dayjs('2016-02-08T00:50'),
  durationRequiredMika: '44013',
  booleanRequiredMika: false,
  enumRequiredMika: EnumRequiredFieldClass['ENUM_VALUE_2'],
  uuidRequiredMika: '649d087a-83fd-4db1-9ec3-acd7f79db5a1',
  byteImageRequiredMika: '../fake-data/blob/hipster.png',
  byteImageRequiredMikaContentType: 'unknown',
  byteAnyRequiredMika: '../fake-data/blob/hipster.png',
  byteAnyRequiredMikaContentType: 'unknown',
  byteTextRequiredMika: '../fake-data/blob/hipster.txt',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
