import dayjs from 'dayjs/esm';
import { EnumFieldClass } from 'app/entities/enumerations/enum-field-class.model';
import { EnumRequiredFieldClass } from 'app/entities/enumerations/enum-required-field-class.model';

export interface IFieldTestMapstructAndServiceClassEntity {
  id: string;
  stringEva?: string | null;
  stringRequiredEva?: string | null;
  stringMinlengthEva?: string | null;
  stringMaxlengthEva?: string | null;
  stringPatternEva?: string | null;
  integerEva?: number | null;
  integerRequiredEva?: number | null;
  integerMinEva?: number | null;
  integerMaxEva?: number | null;
  longEva?: number | null;
  longRequiredEva?: number | null;
  longMinEva?: number | null;
  longMaxEva?: number | null;
  floatEva?: number | null;
  floatRequiredEva?: number | null;
  floatMinEva?: number | null;
  floatMaxEva?: number | null;
  doubleRequiredEva?: number | null;
  doubleMinEva?: number | null;
  doubleMaxEva?: number | null;
  bigDecimalRequiredEva?: number | null;
  bigDecimalMinEva?: number | null;
  bigDecimalMaxEva?: number | null;
  localDateEva?: dayjs.Dayjs | null;
  localDateRequiredEva?: dayjs.Dayjs | null;
  instantEva?: dayjs.Dayjs | null;
  instanteRequiredEva?: dayjs.Dayjs | null;
  zonedDateTimeEva?: dayjs.Dayjs | null;
  zonedDateTimeRequiredEva?: dayjs.Dayjs | null;
  durationEva?: string | null;
  durationRequiredEva?: string | null;
  booleanEva?: boolean | null;
  booleanRequiredEva?: boolean | null;
  enumEva?: EnumFieldClass | null;
  enumRequiredEva?: EnumRequiredFieldClass | null;
  uuidEva?: string | null;
  uuidRequiredEva?: string | null;
  byteImageEva?: string | null;
  byteImageEvaContentType?: string | null;
  byteImageRequiredEva?: string | null;
  byteImageRequiredEvaContentType?: string | null;
  byteImageMinbytesEva?: string | null;
  byteImageMinbytesEvaContentType?: string | null;
  byteImageMaxbytesEva?: string | null;
  byteImageMaxbytesEvaContentType?: string | null;
  byteAnyEva?: string | null;
  byteAnyEvaContentType?: string | null;
  byteAnyRequiredEva?: string | null;
  byteAnyRequiredEvaContentType?: string | null;
  byteAnyMinbytesEva?: string | null;
  byteAnyMinbytesEvaContentType?: string | null;
  byteAnyMaxbytesEva?: string | null;
  byteAnyMaxbytesEvaContentType?: string | null;
  byteTextEva?: string | null;
  byteTextRequiredEva?: string | null;
}

export type NewFieldTestMapstructAndServiceClassEntity = Omit<IFieldTestMapstructAndServiceClassEntity, 'id'> & { id: null };
